export const links = [
  {
    name: "Services",
    submenu: true,
    sublinks: [
      {
        // Head: "Managed Defense",
        // sublink: [
        //   { name: "Managed Detection and Response", link: "/mdr" },
        //   { name: "Extended Detection and Response", link: "/xdr" },
        //   { name: "Endpoint Detection and Response", link: "/endpoint-detection" },
        //   { name: "Managed Microsoft Sentinel Detection and Response", link: "/microsoft-detection" },
        //   { name: "Digital Forensics and Incident Response", link: "/digital-forensics" },
        // ],
        Head: "Managed Defense",
        sublink: [
          { name: "Managed Detection and Response", link: "/coming-soon" },
          { name: "Extended Detection and Response", link: "/coming-soon" },
          { name: "Endpoint Detection and Response", link: "/coming-soon" },
          { name: "Managed Microsoft Sentinel Detection and Response", link: "/coming-soon" },
          { name: "Digital Forensics and Incident Response", link: "/coming-soon" },
        ],
        meaning_title: "defense (noun)",
        meaning: "The ability to protect against attack or harm, or something used to protect against attack or harm.",
      },
      {
        // Head: "Managed EndCompute",
        // sublink: [
        //   { name: "Mobile Device Manager", link: "/mobile-manager" },
        //   { name: "Compliance assessment and Remediation", link: "/compliance-assessment" },
        //   { name: "Cross Platform Integration", link: "/cross-platform" },
        //   { name: "Apple Adoption", link: "/apple-adoption" },
        //   { name: "Configuration Health Check", link: "/configuration-check" },
        //   { name: "Hardware Health Check", link: "/hardware-check" },
        //   { name: "Multilingual Helpdesk", link: "/helpdesk" },
        // ],
        Head: "Managed EndCompute",
        sublink: [
          { name: "Mobile Device Manager", link: "/coming-soon" },
          { name: "Compliance assessment and Remediation", link: "/coming-soon" },
          { name: "Cross Platform Integration", link: "/coming-soon" },
          { name: "Apple Adoption", link: "/apple-adoption" },
          { name: "Configuration Health Check", link: "/coming-soon" },
          { name: "Hardware Health Check", link: "/coming-soon" },
          { name: "Multilingual Helpdesk", link: "/helpdesk" },
        ],
        meaning_title: "endcompute (noun)",
        meaning: "Technologies that gives your workforce secure, remote access to applications, desktops, and data.",
      },
      {
        // Head: "Managed Risk",
        // sublink: [
        //   { name: "Penetration Testing", link: "/pentesting" },
        //   { name: "Vulnerability Management as a Service", link: "/vmaas" },
        //   { name: "CISO as a Service", link: "/ciso-services" },
        //   { name: "Cyber Security Controls Assessment", link: "/cybersecurity-controls" },
        //   { name: "Web Application Security Testing", link: "/webapplication-security" },
        //   { name: "Phishing Attack Simulation", link: "/phishing-simulation" },
        // ],
        Head: "Managed Risk",
        sublink: [
          { name: "Penetration Testing", link: "/coming-soon" },
          { name: "Vulnerability Management as a Service", link: "/coming-soon" },
          { name: "CISO as a Service", link: "/ciso-services" },
          { name: "Cyber Security Controls Assessment", link: "/coming-soon" },
          { name: "Web Application Security Testing", link: "/coming-soon" },
          { name: "Phishing Attack Simulation", link: "/coming-soon" },
        ],
        meaning_title: "risk (noun)",
        meaning: "Risk refers to the possibility or likelihood of suffering harm, injury, or loss due to an uncertain event or condition.",
      },
      {
        // Head: "Managed Security",
        // sublink: [
        //   { name: "Managed Endpoint Protection", link: "/epp" },
        //   { name: "Managed Endpoint Security", link: "/endpoint-security" },
        //   { name: "Darktrace/Email as a Service", link: "/darktrace" },
        //   { name: "Managed Data Security", link: "/data-security" },
        //   { name: "Threat and Risk Intelligence", link: "/tri" },
        //   { name: "Identity and Access Management", link: "/iam" },
        // ],
        Head: "Managed Security",
        sublink: [
          { name: "Managed Endpoint Protection", link: "/coming-soon" },
          { name: "Managed Endpoint Security", link: "/coming-soon" },
          { name: "Darktrace/Email as a Service", link: "/coming-soon" },
          { name: "Managed Data Security", link: "/coming-soon" },
          { name: "Threat and Risk Intelligence", link: "/coming-soon" },
          { name: "Identity and Access Management", link: "/coming-soon" },
        ],
        meaning_title: "security (noun)",
        meaning: "The protection of people, organizations, countries, etc. against a possible attack or other crime.",
      },
    ],
  },
];
